CREATE TABLE IF NOT EXISTS `knowledge` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    `category` VARCHAR(50) NOT NULL COMMENT '分类：training/nutrition/general',
    `title` VARCHAR(200) NOT NULL COMMENT '标题',
    `content` TEXT NOT NULL COMMENT '内容',
    `keywords` VARCHAR(500) DEFAULT NULL COMMENT '关键词，逗号分隔',
    `isActive` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
    `createTime` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updateTime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库';
